const MILESTONE_POINTS = 200;
const MS_PER_DAY = 24 * 60 * 60 * 1000;
const CHECK_IN_WINDOW_MIN_DAYS = 7;
const CHECK_IN_WINDOW_MAX_DAYS = 14;

module.exports = {
  MILESTONE_POINTS,
  MS_PER_DAY,
  CHECK_IN_WINDOW_MIN_DAYS,
  CHECK_IN_WINDOW_MAX_DAYS,
};
