apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-engagement

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Add secret.yaml locally after copying from secret.yaml.example
