apiVersion: v1
kind: Service
metadata:
  name: user-engagement-api
  namespace: user-engagement
  labels:
    app: user-engagement-api
spec:
  type: LoadBalancer
  selector:
    app: user-engagement-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
